In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import keras

Using TensorFlow backend.
C:\Users\haris\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\haris\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\haris\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\haris\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset.shape

(10000, 14)

In [8]:
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [9]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [10]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
#Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [12]:
## Concatenate the Data Frames

X=pd.concat([X,geography,gender],axis=1)


In [13]:
## Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)

In [14]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [15]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [16]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
# Initialising the ANN
classifier = Sequential()

In [22]:
classifier

In [21]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'he_uniform',activation='relu',input_dim = 11))


In [23]:
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="he_uniform"))

In [24]:
# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="glorot_uniform"))

In [26]:
# Compiling the ANN
classifier.compile(optimizer = 'Adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [27]:
# Fitting the ANN to the Training set
model_history=classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, nb_epoch = 100)

C:\Users\haris\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  



Train on 5359 samples, validate on 2641 samples
Epoch 1/100
5359/5359 [==============================] - 1s 244us/step - loss: 0.4960 - accuracy: 0.7962 - val_loss: 0.4741 - val_accuracy: 0.7944
Epoch 2/100
5359/5359 [==============================] - 1s 121us/step - loss: 0.4523 - accuracy: 0.7970 - val_loss: 0.4529 - val_accuracy: 0.7899
Epoch 3/100
5359/5359 [==============================] - 1s 118us/step - loss: 0.4369 - accuracy: 0.7947 - val_loss: 0.4442 - val_accuracy: 0.7940
Epoch 4/100
5359/5359 [==============================] - 1s 126us/step - loss: 0.4286 - accuracy: 0.8003 - val_loss: 0.4380 - val_accuracy: 0.7944
Epoch 5/100
5359/5359 [==============================] - 1s 190us/step - loss: 0.4204 - accuracy: 0.8015 - val_loss: 0.4323 - val_accuracy: 0.7993
Epoch 6/100
5359/5359 [==============================] - 1s 115us/step - loss: 0.4110 - accuracy: 0.8052 - val_loss: 0.4248 - val_accuracy: 0.7936
Epoch 7/100
5359/5359 [==============================] - 1s 124us/ste

Epoch 55/100
5359/5359 [==============================] - 1s 152us/step - loss: 0.3279 - accuracy: 0.8625 - val_loss: 0.3532 - val_accuracy: 0.8599
Epoch 56/100
5359/5359 [==============================] - 1s 138us/step - loss: 0.3280 - accuracy: 0.8640 - val_loss: 0.3533 - val_accuracy: 0.8591
Epoch 57/100
5359/5359 [==============================] - 1s 120us/step - loss: 0.3273 - accuracy: 0.8640 - val_loss: 0.3536 - val_accuracy: 0.8610
Epoch 58/100
5359/5359 [==============================] - 1s 118us/step - loss: 0.3276 - accuracy: 0.8630 - val_loss: 0.3537 - val_accuracy: 0.8610
Epoch 59/100
5359/5359 [==============================] - 1s 127us/step - loss: 0.3275 - accuracy: 0.8614 - val_loss: 0.3535 - val_accuracy: 0.8584
Epoch 60/100
5359/5359 [==============================] - 1s 137us/step - loss: 0.3267 - accuracy: 0.8634 - val_loss: 0.3543 - val_accuracy: 0.8546
Epoch 61/100
5359/5359 [==============================] - 1s 125us/step - loss: 0.3273 - accuracy: 0.8632 - val_

In [28]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [29]:
unique, counts = np.unique(y_pred, return_counts=True)

dict(zip(unique, counts))

{False: 1669, True: 331}

In [30]:
unique, counts = np.unique(y_test, return_counts=True)

dict(zip(unique, counts))

{0: 1595, 1: 405}

In [31]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [32]:
cm

array([[1487,  108],
       [ 182,  223]], dtype=int64)

In [33]:
# Calculate the Accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [34]:
score

0.855

In [35]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [36]:
from keras.layers import Activation, Embedding, Flatten, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid
from keras.layers import LeakyReLU

In [37]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [38]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [39]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [40]:
# Splitting the dataset again into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling again
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [41]:
y_train

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

In [42]:
X_train.shape[1]

11

In [43]:
def create_model(layers, activation):
    model = Sequential()
    for i, nodes in enumerate(layers):
        if i==0:
            model.add(Dense(nodes,input_dim=X_train.shape[1]))
            model.add(Activation(activation))
        else:
            model.add(Dense(nodes))
            model.add(Activation(activation))
    model.add(Dense(1)) # Note: no activation beyond this point
    
    model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
    return model
    
model = KerasClassifier(build_fn=create_model, verbose=0)
    

In [44]:
model

In [45]:
layers=[(150,), (160,100), (140,100,500)]
activations = ['sigmoid', 'relu']
param_grid = dict(layers=layers, activation=activations, batch_size = [128, 256], epochs=[30])
grid = GridSearchCV(estimator=model, param_grid=param_grid,cv=5)

In [46]:
grid_result = grid.fit(X_train, y_train)

In [47]:
[grid_result.best_score_,grid_result.best_params_]


[0.8486250042915344,
 {'activation': 'relu', 'batch_size': 256, 'epochs': 30, 'layers': (160, 100)}]

In [48]:
pred_y = grid.predict(X_test)


In [49]:
pred_y

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [50]:
y_pred = (pred_y > 0.5)


In [55]:
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [51]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [52]:
cm

array([[1469,  126],
       [ 185,  220]], dtype=int64)

In [53]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

In [54]:
score

0.8445